# Generated by Django 3.2.6 on 2021-08-03 01:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 1, 56, 50, 433374, tzinfo=utc)),
        ),
    ]
